services:
  api:
    build: .
    container_name: todo-api
    depends_on:
      - db
    ports:
      - "10279:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
    restart: always

  db:
    image: mysql:8
    container_name: mysql-todo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
